#!/bin/bash
# Hermes Agent Stack Setup — Phase 1.5: Native Services
# Installs Ollama and hermes-agent as native host processes (Linux + macOS)
#
# Usage: bash setup-native.sh
# Prev:  bash setup.sh
# Next:  bash setup-services.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

# ── Banner ──────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}"
echo "  ============================================"
echo "  Hermes Agent Stack Setup — Phase 1.5 of 4"
echo "          Native Service Install"
echo "  ============================================"
echo -e "${NC}"

# ══════════════════════════════════════════════
# DETECT OS
# ══════════════════════════════════════════════

OS="$(uname -s)"
case "$OS" in
    Linux)  PLATFORM="linux" ;;
    Darwin) PLATFORM="macos" ;;
    *)
        err "Unsupported operating system: $OS"
        err "setup-native.sh supports Linux and macOS only."
        exit 1
        ;;
esac

log "Platform: $PLATFORM"
echo ""

# ══════════════════════════════════════════════
# RESOLVE INSTALL DIR
# ══════════════════════════════════════════════

INSTALL_DIR="$(resolve_install_dir)"

if [ ! -d "$INSTALL_DIR" ] || [ ! -f "$INSTALL_DIR/.env" ]; then
    err "No installation found at $INSTALL_DIR"
    err "Run setup.sh first to create the foundation."
    exit 1
fi

log "Install directory: $INSTALL_DIR"

# Read tier from .setup-state (written by setup-services.sh, defaults to base)
TIER="base"
if [ -f "$SCRIPT_DIR/.setup-state" ]; then
    STATE_TIER="$(grep '^TIER=' "$SCRIPT_DIR/.setup-state" 2>/dev/null | cut -d= -f2-)"
    [ -n "$STATE_TIER" ] && TIER="$STATE_TIER"
fi
[ -n "${1:-}" ] && TIER="$1"

log "Tier: $TIER"
echo ""

# ══════════════════════════════════════════════
# SOURCE INSTALL_DIR/.env (for secrets)
# ══════════════════════════════════════════════

# shellcheck disable=SC1090
set -a; source "$INSTALL_DIR/.env"; set +a

HERMES_HOME_DIR="$HOME/.hermes"
HERMES_BIN="$HERMES_HOME_DIR/bin/hermes"

# ══════════════════════════════════════════════
# INSTALL OLLAMA
# ══════════════════════════════════════════════

log "Installing Ollama..."

if command -v ollama &>/dev/null; then
    OLLAMA_VER="$(ollama --version 2>/dev/null | head -1 || echo "installed")"
    log "  Ollama already installed: $OLLAMA_VER"
else
    if [ "$PLATFORM" = "linux" ]; then
        log "  Downloading Ollama installer..."
        curl -fsSL https://ollama.ai/install.sh | sh
        log "  Ollama installed"
    elif [ "$PLATFORM" = "macos" ]; then
        log "  Installing Ollama (macOS)..."
        if command -v brew &>/dev/null; then
            brew install ollama
        else
            warn "  Homebrew not found — downloading Ollama app..."
            OLLAMA_TMP="$(mktemp -d)"
            curl -fsSL "https://ollama.ai/download/Ollama-darwin.zip" \
                -o "$OLLAMA_TMP/ollama.zip"
            unzip -q "$OLLAMA_TMP/ollama.zip" -d "$OLLAMA_TMP"
            sudo mkdir -p /usr/local/bin
            sudo cp "$OLLAMA_TMP/Ollama.app/Contents/Resources/ollama" \
                /usr/local/bin/ollama
            rm -rf "$OLLAMA_TMP"
        fi
        log "  Ollama installed"
    fi
fi

echo ""

# ══════════════════════════════════════════════
# INSTALL HERMES-AGENT
# ══════════════════════════════════════════════

log "Installing hermes-agent..."

if [ -f "$HERMES_BIN" ]; then
    log "  hermes-agent already installed at $HERMES_BIN"
elif [ -d "$INSTALL_DIR/src/hermes-agent" ]; then
    log "  Installing from $INSTALL_DIR/src/hermes-agent ..."

    PIP_CMD=""
    if command -v pip3 &>/dev/null; then
        PIP_CMD="pip3"
    elif command -v pip &>/dev/null; then
        PIP_CMD="pip"
    else
        err "pip not found. Install Python 3 and pip first."
        exit 1
    fi

    mkdir -p "$HERMES_HOME_DIR/bin"
    "$PIP_CMD" install --prefix="$HERMES_HOME_DIR" \
        -e "$INSTALL_DIR/src/hermes-agent" > /dev/null 2>&1
    log "  hermes-agent installed to $HERMES_HOME_DIR"
else
    err "hermes-agent source not found at $INSTALL_DIR/src/hermes-agent"
    err "Run setup.sh first to clone hermes-agent."
    exit 1
fi

echo ""

# ══════════════════════════════════════════════
# WRITE ~/.hermes/.env
# ══════════════════════════════════════════════

log "Writing $HERMES_HOME_DIR/.env ..."
mkdir -p "$HERMES_HOME_DIR"

cat > "$HERMES_HOME_DIR/.env" << HERMESENV
# Hermes Agent — generated by setup-native.sh
# Secrets sourced from $INSTALL_DIR/.env

# --- LiteLLM (Docker) ---
LITELLM_BASE_URL=http://localhost:4000/v1
LITELLM_API_KEY=${LITELLM_MASTER_KEY:-}

# --- Agent API ---
HERMES_API_KEY=${API_SERVER_KEY:-}
HERMESENV

if [ "$TIER" = "services" ] || [ "$TIER" = "full" ]; then
    cat >> "$HERMES_HOME_DIR/.env" << SVCENV

# --- MQTT (localhost) ---
MQTT_HOST=localhost
MQTT_PORT=1883

# --- SearXNG (localhost) ---
SEARXNG_URL=http://localhost:8888

# --- Qdrant (localhost) ---
QDRANT_URL=http://localhost:6333
SVCENV
fi

if [ "$TIER" = "full" ]; then
    cat >> "$HERMES_HOME_DIR/.env" << FULLENV

# --- Langfuse (localhost) ---
LANGFUSE_HOST=http://localhost:3100
LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}
LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}
FULLENV
fi

chmod 600 "$HERMES_HOME_DIR/.env"
log "  $HERMES_HOME_DIR/.env written (permissions: 600)"
echo ""

# ══════════════════════════════════════════════
# REGISTER SERVICE
# ══════════════════════════════════════════════

if [ "$PLATFORM" = "linux" ]; then
    # ── Linux: systemd user service ──────────────────────────────
    log "Registering hermes-agent systemd service..."

    if [ -f "$HERMES_BIN" ]; then
        "$HERMES_BIN" gateway install 2>/dev/null || true
    else
        warn "  hermes binary not found at $HERMES_BIN — skipping gateway install"
    fi

    SYSTEMD_UNIT="$HOME/.config/systemd/user/hermes-gateway.service"

    if [ -f "$SYSTEMD_UNIT" ]; then
        if ! grep -q "^EnvironmentFile=" "$SYSTEMD_UNIT"; then
            sed -i '/^\[Service\]/a EnvironmentFile=%h/.hermes/.env' "$SYSTEMD_UNIT"
            log "  Injected EnvironmentFile into $SYSTEMD_UNIT"
        else
            log "  EnvironmentFile already present in $SYSTEMD_UNIT"
        fi

        systemctl --user daemon-reload
        systemctl --user enable --now hermes-gateway
        log "  hermes-gateway service enabled and started"
    else
        warn "  Unit file not found at $SYSTEMD_UNIT"
        warn "  Run manually: $HERMES_BIN gateway install"
    fi

elif [ "$PLATFORM" = "macos" ]; then
    # ── macOS: LaunchAgent plist ─────────────────────────────────
    log "Registering hermes-agent LaunchAgent..."

    PLIST_DIR="$HOME/Library/LaunchAgents"
    PLIST_FILE="$PLIST_DIR/ai.hermes.gateway.plist"
    LOG_DIR="$HERMES_HOME_DIR/logs"

    mkdir -p "$PLIST_DIR" "$LOG_DIR"

    cat > "$PLIST_FILE" << PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>ai.hermes.gateway</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>-c</string>
        <string>set -a; . "${HERMES_HOME_DIR}/.env"; set +a; exec "${HERMES_BIN}" gateway</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/gateway.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/gateway.error.log</string>
</dict>
</plist>
PLISTEOF

    launchctl unload "$PLIST_FILE" 2>/dev/null || true
    launchctl load "$PLIST_FILE"
    log "  LaunchAgent written: $PLIST_FILE"
    log "  Service loaded"
fi

echo ""

# ══════════════════════════════════════════════
# WRITE HERMES-CTL.SH
# ══════════════════════════════════════════════

log "Writing hermes-ctl.sh..."
mkdir -p "$INSTALL_DIR/scripts"

cat > "$INSTALL_DIR/scripts/hermes-ctl.sh" << 'CTLEOF'
#!/bin/bash
# hermes-ctl.sh — Control the native hermes-agent service
# Usage: hermes-ctl.sh [start|stop|restart|status|logs]
set -euo pipefail

PLATFORM="$(uname -s)"

case "${1:-status}" in
    start)
        if [ "$PLATFORM" = "Darwin" ]; then
            launchctl start ai.hermes.gateway
        else
            systemctl --user start hermes-gateway
        fi
        echo "hermes-agent started"
        ;;
    stop)
        if [ "$PLATFORM" = "Darwin" ]; then
            launchctl stop ai.hermes.gateway
        else
            systemctl --user stop hermes-gateway
        fi
        echo "hermes-agent stopped"
        ;;
    restart)
        if [ "$PLATFORM" = "Darwin" ]; then
            launchctl stop ai.hermes.gateway 2>/dev/null || true
            sleep 1
            launchctl start ai.hermes.gateway
        else
            systemctl --user restart hermes-gateway
        fi
        echo "hermes-agent restarted"
        ;;
    status)
        if [ "$PLATFORM" = "Darwin" ]; then
            launchctl list | grep hermes || echo "hermes-agent: not running"
        else
            systemctl --user status hermes-gateway
        fi
        ;;
    logs)
        if [ "$PLATFORM" = "Darwin" ]; then
            LOGFILE="$HOME/.hermes/logs/gateway.log"
            if [ -f "$LOGFILE" ]; then
                tail -f "$LOGFILE"
            else
                echo "No log file found at $LOGFILE"
            fi
        else
            journalctl --user -u hermes-gateway -f
        fi
        ;;
    *)
        echo "Usage: $(basename "$0") [start|stop|restart|status|logs]"
        exit 1
        ;;
esac
CTLEOF

chmod +x "$INSTALL_DIR/scripts/hermes-ctl.sh"
log "  $INSTALL_DIR/scripts/hermes-ctl.sh"

echo ""

# ══════════════════════════════════════════════
# DONE
# ══════════════════════════════════════════════

echo ""
echo -e "${BOLD}"
echo "  ============================================"
echo "   Phase 1.5 Complete — Native Services"
echo "  ============================================"
echo -e "${NC}"
echo "  Ollama:         http://localhost:11434"
echo "  hermes-agent:   http://localhost:8642"
echo "  Config:         $HERMES_HOME_DIR/.env"
echo "  Tier:           $TIER"
echo ""
echo "  Useful commands:"
echo "    ollama pull hermes3:8b"
echo "    bash $INSTALL_DIR/scripts/hermes-ctl.sh status"
echo "    bash $INSTALL_DIR/scripts/hermes-ctl.sh logs"
echo ""
echo -e "  ${BOLD}Next: bash setup-services.sh${NC}"
echo "  Pick a service tier and start Docker containers."
echo ""
