#!/bin/bash
# Evey Stack Setup — get a hermes-agent stack running in minutes
# Usage: curl -sf https://raw.githubusercontent.com/42-evey/evey-setup/main/setup.sh | bash
set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${GREEN}[evey-setup]${NC} $1"; }
err() { echo -e "${RED}[evey-setup]${NC} $1" >&2; }
ask() { echo -en "${CYAN}[evey-setup]${NC} $1: "; read -r REPLY; }

INSTALL_DIR="${EVEY_DIR:-$HOME/evey-stack}"

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║      Evey Stack Setup v1.0           ║"
echo "  ║  hermes-agent + LiteLLM + plugins    ║"
echo "  ╚══════════════════════════════════════╝"
echo ""

# ── Phase 1: Prerequisites ──
log "Checking prerequisites..."

check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        err "$1 not found. Please install it first."
        return 1
    fi
    log "  ✓ $1 found"
}

check_cmd docker || exit 1
check_cmd git || exit 1

if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
    err "Docker Compose not found. Install Docker Desktop or docker-compose-plugin."
    exit 1
fi
log "  ✓ Docker Compose found"

# Check Docker is running
if ! docker info &>/dev/null; then
    err "Docker is not running. Please start Docker first."
    exit 1
fi
log "  ✓ Docker is running"

# ── Phase 2: API Keys ──
echo ""
log "Setting up API keys..."
echo ""

ask "OpenRouter API key (get one at openrouter.ai/keys, or press Enter to skip)"
OPENROUTER_KEY="$REPLY"

ask "Telegram bot token (from @BotFather, or press Enter to skip)"
TELEGRAM_TOKEN="$REPLY"

# Generate random keys for internal services
LITELLM_KEY="sk-evey-$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | xxd -p)"
API_KEY="sk-api-$(openssl rand -hex 8 2>/dev/null || head -c 16 /dev/urandom | xxd -p)"

# ── Phase 3: Clone and Setup ──
echo ""
log "Setting up in $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Clone hermes-agent
if [ ! -d "src/hermes-agent" ]; then
    log "Cloning hermes-agent..."
    mkdir -p src
    git clone --depth 1 https://github.com/NousResearch/hermes-agent.git src/hermes-agent
fi

# Clone plugins
if [ ! -d "plugins" ]; then
    log "Cloning Evey plugins..."
    git clone --depth 1 https://github.com/42-evey/hermes-plugins.git plugins
fi

# ── Phase 4: Write configs ──
log "Writing configuration..."

# .env
cat > .env << ENVEOF
# Generated by evey-setup
OPENROUTER_API_KEY=${OPENROUTER_KEY}
TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
LITELLM_MASTER_KEY=${LITELLM_KEY}
API_SERVER_KEY=${API_KEY}
TZ=$(cat /etc/timezone 2>/dev/null || echo "UTC")
ENVEOF

# docker-compose.yml
cat > docker-compose.yml << 'DCEOF'
services:
  hermes-agent:
    build:
      context: .
      dockerfile: src/hermes-agent/Dockerfile
    container_name: hermes-agent
    volumes:
      - ./data/hermes:/home/hermes/.hermes
      - ./plugins:/home/hermes/.hermes/plugins/community
    environment:
      HERMES_PROVIDER: openrouter
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_BASE_URL: http://hermes-litellm:4000/v1
      OPENAI_API_KEY: ${LITELLM_MASTER_KEY}
      API_SERVER_ENABLED: "true"
      API_SERVER_PORT: "8642"
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_KEY: ${API_SERVER_KEY}
      TZ: ${TZ}
    ports:
      - "127.0.0.1:8642:8642"
    depends_on:
      hermes-litellm:
        condition: service_healthy
    networks:
      - evey-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  hermes-litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: hermes-litellm
    volumes:
      - ./config/litellm.yaml:/app/config.yaml
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    ports:
      - "127.0.0.1:4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:4000/health/liveliness')\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - evey-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  hermes-ollama:
    image: ollama/ollama:latest
    container_name: hermes-ollama
    environment:
      OLLAMA_KEEP_ALIVE: "30m"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "127.0.0.1:11434:11434"
    networks:
      - evey-net
    restart: unless-stopped

networks:
  evey-net:
    driver: bridge
DCEOF

# LiteLLM config with free models
mkdir -p config
cat > config/litellm.yaml << 'LMEOF'
model_list:
  - model_name: brain
    litellm_params:
      model: openai/xiaomi/mimo-v2-pro
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: "https://openclaw.ai"
        X-OpenRouter-Title: "OpenClaw"
      extra_body:
        reasoning:
          exclude: true
      input_cost_per_token: 0
      output_cost_per_token: 0

  - model_name: nemotron-free
    litellm_params:
      model: openai/nvidia/nemotron-3-super-120b-a12b:free
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1

  - model_name: llama70b-free
    litellm_params:
      model: openai/meta-llama/llama-3.3-70b-instruct:free
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1

fallbacks:
  - brain: [nemotron-free, llama70b-free]

litellm_settings:
  max_budget: 5.0
  budget_duration: 1d
  cache: true
  cache_params:
    type: "local"
    ttl: 300

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
LMEOF

# Create data dirs
mkdir -p data/hermes

# ── Phase 5: Install plugins ──
log "Installing plugins..."
mkdir -p data/hermes/plugins
cp -r plugins/evey-* data/hermes/plugins/ 2>/dev/null || true
cp plugins/evey_utils.py data/hermes/plugins/ 2>/dev/null || true

# ── Phase 6: Start ──
echo ""
log "Starting services..."
docker compose up -d 2>&1 | tail -5

echo ""
log "Waiting for services to start..."
sleep 15

# Health check
if curl -sf http://localhost:4000/health/liveliness > /dev/null 2>&1; then
    log "✓ LiteLLM is healthy"
else
    err "LiteLLM not responding yet — may need more time"
fi

if curl -sf http://localhost:8642/health > /dev/null 2>&1; then
    log "✓ Hermes agent is healthy"
else
    err "Hermes agent not responding yet — may need more time"
fi

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║          Setup Complete!             ║"
echo "  ╠══════════════════════════════════════╣"
echo "  ║  Directory: $INSTALL_DIR"
echo "  ║  Agent API: http://localhost:8642    ║"
echo "  ║  LiteLLM:   http://localhost:4000    ║"
echo "  ║  Brain:     MiMo-V2-Pro (FREE)      ║"
echo "  ║                                      ║"
echo "  ║  Plugins: 42-evey/hermes-plugins     ║"
echo "  ║  Docs: github.com/42-evey            ║"
echo "  ╚══════════════════════════════════════╝"
echo ""
log "Run 'docker compose logs -f hermes-agent' to see logs"
log "Run 'hermes gateway setup' to configure Telegram"
